### PR TITLE
Add note about `allow` rules

### PR DESCRIPTION
**Pull request by SheetJSDev**
See https://github.com/wooorm/alex/issues/176

(screenshot should eventually be updated)

### CODE REVIEW

**Comment by wooorm** [comment]
Thank you!!!

Do you think this small note will make it clearer what the rule sources are? Or do we need more?

**Comment by SheetJSDev** [comment]
Revisiting the issue a week later, the original confusion surrounded exactly what the `allow` field contained.  The two examples in the README were `boogeyman-boogeywoman` and `butt`, both of which happened to match the offending text, so it wasn't clear that you needed to specify the rule id.  I think the one-sentence clarification suffices.

**Comment by wooorm** [comment]
Alright, great!

**Comment by wooorm** [comment]
Thanks so much @SheetJSDev!

**Pull request merged**
