### PR TITLE
Rebuild files.

### PR DESCRIPTION
**Pull request by jdalton**
This PR rebuilds alex using the updated es5-shim package `object-keys` which avoids errors in IE / Edge when checking for properties that throw because of a CSP policy or other restrictions.

I simply did:
```bash
npm i
npm run build
```

### CODE REVIEW

**Comment by patrickkettner** [comment]
what are the "other" restrictions?

**Comment by jdalton** [comment]
`object-keys` originally [added guards](https://github.com/ljharb/object-keys/commit/176f03335e90d5c8d0d8125a99f27819c9b9cdad) for a few properties that errored when compared, e.g. `localStorage.constructor.prototype === localStorage`.

**Comment by wooorm** [comment]
Thanks @jdalton! For some weird reason when I did the same (after `rm -rf node_modules`) I came up with a few differences. Not sure what’s going on. I’m on `node -v 5.0.0`?

Anyway, I amended your commit to keep your name intact!

**Comment by jdalton** [comment]
Rock!

**Pull request closed without merging**
